### ISSUE TITLE
Error load savegame

### ISSUE THREAD

**Issue by ravea** [AndorsTrailRelease/andors-trail#44]
android 6.0.1, CM13, russian and english languages, version 0.8.1

`java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoSuchMethodError: No virtual method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/HashMap; or its super classes (declaration of 'java.util.HashMap' appears in /system/framework/core-libart.jar)
	at com.gpl.rpg.AndorsTrail.model.GameStatistics.<init>(GameStatistics.java:189)
	at com.gpl.rpg.AndorsTrail.model.ModelContainer.<init>(ModelContainer.java:36)
	at com.gpl.rpg.AndorsTrail.savegames.Savegames.loadWorld(Savegames.java:216)
	at com.gpl.rpg.AndorsTrail.savegames.Savegames.loadWorld(Savegames.java:107)
	at com.gpl.rpg.AndorsTrail.WorldSetup.continueWorld(WorldSetup.java:149)
	at com.gpl.rpg.AndorsTrail.WorldSetup.access$700(WorldSetup.java:15)
	at com.gpl.rpg.AndorsTrail.WorldSetup$2.doInBackground(WorldSetup.java:118)
	at com.gpl.rpg.AndorsTrail.WorldSetup$2.doInBackground(WorldSetup.java:109)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more`

Not found `GetOrDefault` on class HashMap

**Comment by ravea** [comment]
@NutAndor, Can you make a new version with this fix and update translations?
 https://github.com/AndorsTrailRelease/andors-trail/pull/46
